image: python:latest
services: 
  - postgres:latest
variables:
    POSTGRES_HOST: postgres
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: ""
    POSTGRES_HOST_AUTH_METHOD: trust
    SECRET_KEY: e1hw&2g1=9(5=z+_fziv5x8=^qq6tj(s66tsceh$%g%x#3%2em
stages:
  - test

test:
  stage: test
  script:
    # this configures Django application to use attached postgres database that is run on `postgres` host
    - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
    #- apt-get update -qy
    #- apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - python manage.py test api.tests --settings=DEEMO.settings.test