# Generated by Django 3.1.2 on 2020-12-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_CategoryLoad'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
