# Generated by Django 3.1.2 on 2020-12-29 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_mail_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatComment',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DATE', models.DateTimeField()),
                ('TEXT', models.CharField(blank=True, max_length=600, null=True)),
                ('CONTACT_ID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('DEBATE_ID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.debate')),
            ],
        ),
    ]
