# Generated by Django 3.1.2 on 2021-01-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcomment',
            name='CONTACT_NAME',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
