# Generated by Django 3.1.2 on 2021-01-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chatcomment_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='ACTIVITY_SCORE',
            field=models.IntegerField(default=0),
        ),
    ]
