# Generated by Django 3.1.2 on 2021-01-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_debate_activity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='LATITUDE',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='debate',
            name='LONGITUDE',
            field=models.FloatField(null=True),
        ),
    ]
