# Generated by Django 3.1.2 on 2021-01-17 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210115_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentChatComments',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CONTACT_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('DATE', models.DateTimeField(auto_now_add=True)),
                ('TEXT', models.CharField(blank=True, max_length=600, null=True)),
                ('CONTACT_ID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('DEBATE_ID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.debate')),
            ],
        ),
    ]
