# Generated by Django 3.1.2 on 2021-02-07 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_debate_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('PATH', models.CharField(blank=True, max_length=600, null=True)),
                ('APPROVED', models.IntegerField(default=1)),
                ('DEBATE_ID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.debate')),
            ],
        ),
    ]
